### PR TITLE
Adding peter to the project

### PR DESCRIPTION
**Pull request by PeterBell**
Because why not?!

### CODE REVIEW

**Comment by PeterBell** [comment]
I think it looks OK - anyone else?

**Comment by franks999** [comment]
Looks good

**Comment by rsummitt** [comment]
:+1: :+1: :+1: :+1: :+1:

**Comment by PeterBell** [comment]
:+1: :-1: ready to :ship: it

**Comment by ghost** [comment]
:hankey:

**Comment by PeterBell** [comment]
colbert

**Pull request merged**
